sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Posts, Categoria]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Contactos]


    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
